name: Monitoramento Diário ITPS

on:
  schedule:
    # Os números 1-5 no final garantem que vai rodar apenas de Segunda a Sexta
    - cron: '30 9 * * 1-5'   # 06:30 no Brasil
    - cron: '0 13 * * 1-5'   # 10:00 no Brasil
    - cron: '15 16 * * 1-5'  # 13:15 no Brasil
    - cron: '0 19 * * 1-5'   # 16:00 no Brasil
  workflow_dispatch: # Permite rodar manualmente clicando no botão

jobs:
  buscar_itps:
    runs-on: ubuntu-latest
    permissions:
      issues: write # PERMISSÃO CRÍTICA PARA GRAVAR MEMÓRIA
      contents: read
    
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar Robô
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python main.py
