name: Monitoramento Diário ITPS

on:
  schedule:
    - cron: '0 10-22 * * *' # Roda de hora em hora (horário comercial)
  workflow_dispatch: # Permite rodar manualmente clicando no botão

jobs:
  buscar_itps:
    runs-on: ubuntu-latest
    permissions:
      issues: write # PERMISSÃO CRÍTICA PARA GRAVAR MEMÓRIA
      contents: read
    
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar Robô
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python main.py
